version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      # Log in to Amazon ECR
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)

      # Build the Docker image
      - echo Building Docker image...
      - docker build -t my-docker-repo .

      # Tag the Docker image with the ECR repository URI
      - docker tag my-docker-repo:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest

      # Push the Docker image to Amazon ECR
      - echo Pushing Docker image to Amazon ECR...
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:latest

artifacts:
  files:
    - imagedefinitions.json
